#Experiment No.10
##Ayush Dumbre
##Entc, A-2
##PRN-25070123029
##Create a dataset and load dataset

In [2]:
#dataset creation
import pandas as pd
data={
    'Roll No.':['1','2','3','4','5'],
    'grender':['female','male','female','male','female'],
    'department':['entc','cse','it','mech','civil'],
    'cgpa':[8.2,9,7.8,9.3,7.7]
}
df=pd.DataFrame(data)
df.to_csv('student.csv',index=False)
df

  Roll No. grender department  cgpa
0        1  female       entc   8.2
1        2    male        cse   9.0
2        3  female         it   7.8
3        4    male       mech   9.3
4        5  female      civil   7.7

In [3]:
#adding a new column
df['age']=[17,18,19,18,19]
df

  Roll No. grender department  cgpa  age
0        1  female       entc   8.2   17
1        2    male        cse   9.0   18
2        3  female         it   7.8   19
3        4    male       mech   9.3   18
4        5  female      civil   7.7   19

In [4]:
df.shape

(5, 5)

In [5]:
df.size

25

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll No.    5 non-null      object
 1   grender     5 non-null      object
 2   department  5 non-null      object
 3   cgpa        5 non-null      float64
 4   age         5 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [9]:
df.describe()

           cgpa       age
count  5.000000   5.00000
mean   8.400000  18.20000
std    0.717635   0.83666
min    7.700000  17.00000
25%    7.800000  18.00000
50%    8.200000  18.00000
75%    9.000000  19.00000
max    9.300000  19.00000

In [10]:
#access information of column department
df['department']

0     entc
1      cse
2       it
3     mech
4    civil
Name: department, dtype: object

In [22]:
#access information of PRN 103
df.loc[2]

Roll No.        3
department     it
cgpa          7.8
age            19
grade           B
Name: 2, dtype: object

In [11]:
#find out data types of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll No.    5 non-null      object
 1   grender     5 non-null      object
 2   department  5 non-null      object
 3   cgpa        5 non-null      float64
 4   age         5 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [17]:
#perform mean, median ,mode operation
mean1=df['cgpa'].mean()
median1=df['cgpa'].median()
mode1=df['cgpa'].mode()
print(mean1)
print(median1)
print(mode1)

8.4
8.2
0    7.7
1    7.8
2    8.2
3    9.0
4    9.3
Name: cgpa, dtype: float64

In [14]:
#insert a new column grade
df['grade']=['B+','A','B','A+','B']
df

  Roll No. grender department  cgpa  age grade
0        1  female       entc   8.2   17    B+
1        2    male        cse   9.0   18     A
2        3  female         it   7.8   19     B
3        4    male       mech   9.3   18    A+
4        5  female      civil   7.7   19     B

In [18]:
#delete gender column
df.drop('grender',axis=1,inplace=True)
df

  Roll No. department  cgpa  age grade
0        1       entc   8.2   17    B+
1        2        cse   9.0   18     A
2        3         it   7.8   19     B
3        4       mech   9.3   18    A+
4        5      civil   7.7   19     B

In [20]:
#cgpa of topper
print('topper gpa:',df['cgpa'].max())

topper gpa: 9.3

In [21]:
#cpga of PRN 105
print('PRN 105 gpa:',df.loc[4,'cgpa'])

PRN 105 gpa: 7.7

In [27]:
#uploading a dataset to read
df=pd.read_csv('/content/Cars93.csv')
import numpy as np
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [28]:
df.size

930

In [29]:
df.shape

(93, 10)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [36]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [34]:
display(df.head())

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [35]:
display(df.tail())

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [37]:
df=pd.read_csv('/content/library_records_500 - Sheet1.csv')
df

,unique id,name,year of study,department,book serial no.,book name,date of issue,submit date,phone no.,email id
0,STU1001,Vikram Das,3,Mathematics,BK-69868,The Alchemist,2025-10-10,2025-10-29,9192009434,vikram.das93@university.edu
1,STU1002,Kabir Patel,1,Electrical Engineering,BK-26499,Calculus Early Transcendentals,2025-02-08,2025-02-17,7293165521,kabir.patel45@university.edu
2,STU1003,Pooja Gupta,4,Computer Science,BK-83443,1984,2025-06-05,2025-06-15,9421591928,pooja.gupta64@university.edu
3,STU1004,Karan Nair,3,Mechanical Engineering,BK-66865,Psychology of Money,2025-07-24,2025-08-10,9973599262,karan.nair75@university.edu
4,STU1005,Riya Singh,4,Civil Engineering,BK-16027,The Alchemist,2025-10-21,2025-10-28,9599188852,riya.singh66@university.edu
...,...,...,...,...,...,...,...,...,...,...
495,STU1496,Amit Nair,2,Computer Science,BK-11394,The Art of War,2025-03-06,2025-03-24,7807886312,amit.nair53@university.edu
496,STU1497,Pooja Iyer,1,Mathematics,BK-63968,1984,2025-07-06,2025-07-19,9087958624,pooja.iyer86@university.edu
497,STU1498,Meera Nair,3,Electrical Engineering,BK-37853,Physics for Scientists,2025-08-01,2025-08-22,7025387114,meera.nair51@university.edu
498,STU1499,Kabir Verma,3,Electrical Engineering,BK-60045,The Alchemist,2025-07-30,2025-08-13,9439015003,kabir.verma60@university.edu
499,STU1500,Pooja Verma,1,Electrical Engineering,BK-74167,Microbiology Intro,2025-08-31,2025-09-11,8967154391,pooja.verma51@university.edu

In [38]:
df.shape

(500, 10)

In [39]:
df.size

5000

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   unique id        500 non-null    object
 1   name             500 non-null    object
 2   year of study    500 non-null    int64
 3   department       500 non-null    object
 4   book serial no.  500 non-null    object
 5   book name        500 non-null    object
 6   date of issue    500 non-null    object
 7   submit date      500 non-null    object
 8   phone no.        500 non-null    int64
 9   email id         500 non-null    object
dtypes: int64(2), object(8)
memory usage: 39.2+ KB

In [41]:
df.describe()

       year of study     phone no.
count     500.000000  5.000000e+02
mean        2.518000  8.471064e+09
std         1.129703  8.847101e+08
min         1.000000  7.004571e+09
25%         1.000000  7.710076e+09
50%         3.000000  8.433678e+09
75%         4.000000  9.246316e+09
max         4.000000  9.991367e+09

In [42]:
display(df.head())

,unique id,name,year of study,department,book serial no.,book name,date of issue,submit date,phone no.,email id
0,STU1001,Vikram Das,3,Mathematics,BK-69868,The Alchemist,2025-10-10,2025-10-29,9192009434,vikram.das93@university.edu
1,STU1002,Kabir Patel,1,Electrical Engineering,BK-26499,Calculus Early Transcendentals,2025-02-08,2025-02-17,7293165521,kabir.patel45@university.edu
2,STU1003,Pooja Gupta,4,Computer Science,BK-83443,1984,2025-06-05,2025-06-15,9421591928,pooja.gupta64@university.edu
3,STU1004,Karan Nair,3,Mechanical Engineering,BK-66865,Psychology of Money,2025-07-24,2025-08-10,9973599262,karan.nair75@university.edu
4,STU1005,Riya Singh,4,Civil Engineering,BK-16027,The Alchemist,2025-10-21,2025-10-28,9599188852,riya.singh66@university.edu

In [43]:
display(df.tail())

,unique id,name,year of study,department,book serial no.,book name,date of issue,submit date,phone no.,email id
495,STU1496,Amit Nair,2,Computer Science,BK-11394,The Art of War,2025-03-06,2025-03-24,7807886312,amit.nair53@university.edu
496,STU1497,Pooja Iyer,1,Mathematics,BK-63968,1984,2025-07-06,2025-07-19,9087958624,pooja.iyer86@university.edu
497,STU1498,Meera Nair,3,Electrical Engineering,BK-37853,Physics for Scientists,2025-08-01,2025-08-22,7025387114,meera.nair51@university.edu
498,STU1499,Kabir Verma,3,Electrical Engineering,BK-60045,The Alchemist,2025-07-30,2025-08-13,9439015003,kabir.verma60@university.edu
499,STU1500,Pooja Verma,1,Electrical Engineering,BK-74167,Microbiology Intro,2025-08-31,2025-09-11,8967154391,pooja.verma51@university.edu